### ISSUE TITLE
Will this go into the repo?

### ISSUE THREAD

**Issue by schemar** [AidanGlickman/obsidian-nord-enhanced#1]
Any chance I will be able to get this from the official theme browser? Did/will you add this? Would love this on mobile.

**Comment by AidanGlickman** [comment]
That's coming! I'm away right now but when i get back I'll get it up there. Main issue right now is i need a good example vault for a screenshot, but if you'd like to contribute one feel free!

**Comment by schemar** [comment]
My vault is way too unimpressive 🙈 looking forward to getting the theme from within obsidian!

**Comment by AidanGlickman** [comment]
I forgot to close this issue 🤪 happy to announce that this theme is available through obsidian!
